### ISSUE TITLE
Allow passing of all environmental variables

### ISSUE THREAD

**Issue by NopeNopeGuy** [firebuild/firebuild#1278]
Currently, in AOSP's build system, one has to edit firebuild.conf and manually add every single variable manually (there are quite a lot of them), this is just not feasible, so I suggest an option that allows all variables to pass through

**Comment by rbalint** [comment]
Interesting. Since environment variables are considered as process inputs the concept behind passing through very few of them is making the builds more similar, thus reaching higher cache hit rate.
Passing through a lot of variables is painful this way, I see.
As a quick workaround this may work for you and you could even filter variables to pass through:
```
rbalint@nano:~$ firebuild $(printenv | sed 's/=.*/"/;s/^/--option=env_vars.pass_through+="/;') -- bash -c set | tail
XDG_DATA_DIRS=/usr/share/i3:/usr/share/gnome:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop
XDG_RUNTIME_DIR=/run/user/1000
XDG_SEAT=seat0
XDG_SESSION_CLASS=user
XDG_SESSION_DESKTOP=i3
XDG_SESSION_ID=3
XDG_SESSION_TYPE=x11
XDG_VTNR=2
XMODIFIERS=@im=ibus
_=/usr/bin/firebuild
# compared to the default setting:
rbalint@nano:~$ firebuild  -- bash -c set | tail
PATH=/usr/lib/ccache:/home/rbalint/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin
PPID=434326
PS4='+ '
PWD=/home/rbalint
SHELL=/bin/bash
SHELLOPTS=braceexpand:hashall:interactive-comments
SHLVL=1
TERM=dumb
UID=1000
_=bash
rbalint@nano:~$ 

```
I think a single option for passing through all variables would risk leaking in random-based values or secrets.
How about allowing `glob`s in `env_vars.pass_through` to filter for presumably similarly named variables or just allowing setting "*" to pass through everything?

**Comment by NopeNopeGuy** [comment]
Allowing setting "*" would be best as there are way too many unique variables, I also have some errors related to javac on AOSP caused by firebuild, I'll share them when I can, thanks for everything

**Comment by rbalint** [comment]
I went with adding regexp-based filtering to keep it more flexible at the expense of being slightly more complicated to newcomers.
